name: Docker

on: [push]

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: admission-webhook:v1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: CGO_ENABLED=0 GOOS=linux GO111MODULE=on go build -a -installsuffix cgo -o /tmp/admission-webhook

  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag webhookimage 

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_PASSWD }}" | docker login -u "${{ secrets.DOCKERHUB_USER }}" --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=gsakun/admission-webbook
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag webhookimage $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
